
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let current=0;let tab='notes';let toastTimer;const notes=[
{title:'Планы на осень',body:'Собрать важное в одном месте. Оставить больше времени для работы, которая действительно увлекает.',preview:'Идеи, задачи и немного свободного времени.',tag:'Личное',date:'Сегодня, 10:42'},
{title:'После встречи с командой',body:'Обсудили прототип. На следующей встрече проверим сценарий работы без интернета и передачу файлов между устройствами.',preview:'Решения, которые стоит сохранить.',tag:'Работа',date:'Сегодня, 09:15'},
{title:'Что взять в поездку',body:'Паспорт, зарядка, наушники и книга. Скачать билеты на телефон заранее, чтобы они были доступны без сети.',preview:'Небольшой список перед дорогой.',tag:'Поездки',date:'Вчера'},
{title:'Идеи для личного проекта',body:'Простое место для заметок. Мысль можно начать на телефоне, а продолжить вечером на компьютере.',preview:'Меньше переключений, больше смысла.',tag:'Идеи',date:'24 сентября'},
{title:'Книги на выходные',body:'Выбрать одну книгу и оставить телефон в другой комнате. Выписать три мысли, которые хочется запомнить.',preview:'Читать медленно и делать пометки.',tag:'Личное',date:'23 сентября'},
{title:'Полезные ссылки',body:'Документация проекта, материалы по типографике и заметки о локальном хранении данных.',preview:'Материалы для следующего шага.',tag:'Работа',date:'22 сентября'}];
const tasks=[{text:'Разобрать заметки с телефона',done:true},{text:'Набросать план личного проекта',done:false},{text:'Отправить материалы на ноутбук',done:false}];
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(s){$('#toast').textContent=s;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3800);}
function renderList(){$('[data-tab=notes] b').textContent=notes.length;const q=$('#search').value.toLowerCase();$('#notes').innerHTML=notes.map((n,i)=>({n,i})).filter(({n})=>(n.title+' '+n.body).toLowerCase().includes(q)).map(({n,i})=>'<button class="note '+(i===current?'active':'')+'" data-note="'+i+'"><strong>'+escapeHTML(n.title)+'</strong><p>'+escapeHTML(n.preview)+'</p><small>'+n.date+' · '+n.tag+'</small></button>').join('')||'<p class="empty">Ничего не найдено.<br>Попробуйте другое слово.</p>';}
function taskHTML(){return tasks.map((t,i)=>'<label class="checkrow"><input type="checkbox" data-task="'+i+'" '+(t.done?'checked':'')+'><span>'+t.text+'</span></label>').join('');}
function showNote(){const n=notes[current];$('#sheet').innerHTML='<div class="eyebrow">'+(document.body.classList.contains('variant-journal')?'26 сентября · суббота':'Место для ваших мыслей')+'</div><h1>'+escapeHTML(n.title)+'</h1><div class="byline"><span>'+n.date+'</span><span># '+n.tag+'</span><span>Markdown</span></div><p class="intro">'+escapeHTML(n.body)+'</p><h3>На этой неделе</h3><div id="tasklist">'+taskHTML()+'</div><div class="attachment"><span class="file-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h7l2 3h9v12H3z"/></svg></span><div><strong>Материалы проекта.pdf</strong><small>2,4 МБ · Доступен офлайн</small></div><button data-action="transfer" aria-label="Передать файл"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 12h16"/><path d="M14 6l6 6-6 6"/></svg></button></div><p class="muted" style="font-size:11px;line-height:1.7">Начните здесь. Продолжите на любом устройстве.</p>';$('.crumb').textContent='Все заметки / '+n.title;if(n.title!=='Планы на осень'){for(const el of $('#sheet h3, #tasklist, #sheet .attachment'))el.remove();}}
function switchTab(next){tab=next;document.body.classList.remove('list-open');document.body.classList.toggle('view-wide',tab!=='notes');$$('.nav').forEach(n=>{n.classList.toggle('active',n.dataset.tab===tab);n.setAttribute('aria-current',n.dataset.tab===tab?'page':'false')});$('.crumb').textContent=({notes:'Все заметки',tasks:'Задачи',files:'Файлы',devices:'Устройства'})[tab];if(tab==='notes'){showNote();renderList();return}if(tab==='tasks'){$('#sheet').innerHTML='<div class="eyebrow">По одному шагу</div><h1>Ваши задачи</h1><p class="intro">Всё, что хочется довести до конца.</p><h3>Планы на осень</h3><div id="tasklist">'+taskHTML()+'</div><p class="cloud-explain">Отметки связаны с исходной заметкой. В этом макете изменения сохраняются только до обновления страницы.</p>';return}if(tab==='files'){$('#sheet').innerHTML='<div class="eyebrow">Под рукой на всех устройствах</div><div class="page-heading"><h1>Ваши файлы</h1><button class="primary" data-action="upload">Добавить файл</button></div><p class="muted" style="font-size:13px">Вложения к заметкам и отдельные файлы</p><table class="filetable"><thead><tr><th>Название</th><th>Размер</th><th>Доступность</th><th>Действие</th></tr></thead><tbody><tr><td>Материалы проекта.pdf</td><td>2,4 МБ</td><td>Офлайн</td><td><button data-action="transfer">Передать</button></td></tr><tr><td>Эскизы.zip</td><td>18 МБ</td><td>В облаке</td><td><button data-action="download">Скачать</button></td></tr><tr><td>Маршрут.pdf</td><td>840 КБ</td><td>Офлайн</td><td><button data-action="transfer">Передать</button></td></tr></tbody></table><div class="cloud-explain"><strong>Копия или синхронизация?</strong><br>«Передать» отправляет независимую копию выбранному устройству. Файлы в этом разделе остаются в общем хранилище аккаунта.</div>';return}$('#sheet').innerHTML='<div class="eyebrow">Связь между устройствами</div><h1>Ваши устройства</h1><p class="intro">Мысли остаются с вами, даже когда меняется экран.</p>'+[['Этот телефон',(new URLSearchParams(location.search).get('platform')==='android'?'Android':'iOS')+' · это устройство','Сейчас'],['Личный компьютер','macOS · последнее подключение 10:41','1 мин назад'],['Рабочий ноутбук','Windows · последнее подключение 10:37','5 мин назад']].map(d=>'<div class="device"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 4h15v11H3z"/><path d="M8 19h5"/><path d="M10 15v4"/><path d="M19 10h3v11h-6v-5"/></svg><div><strong>'+d[0]+'</strong><small>'+d[1]+'</small></div><span class="online">'+d[2]+'</span></div>').join('')+'<div class="cloud-explain"><strong>Где хранятся данные</strong><br>Заметки сохраняются на этом устройстве и в вашем облачном аккаунте. Файлы можно скачать для работы без интернета.<br><br>Это демонстрационные устройства. Облачное подключение в макете отсутствует.</div>';}
function modal(title,body,action){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog-confirm').hidden=!action;$('#dialog-confirm').dataset.confirm=action||'';$('#dialog-confirm').textContent=action==='transfer'?'Показать передачу':'Готово';$('#dialog').showModal();}
document.addEventListener('click',e=>{const n=e.target.closest('[data-note]');if(n){current=Number(n.dataset.note);document.body.classList.remove('list-open');showNote();renderList();return}const nav=e.target.closest('[data-tab]');if(nav){switchTab(nav.dataset.tab);return}const a=e.target.closest('[data-action]');if(!a)return;switch(a.dataset.action){case 'list':if(tab!=='notes')switchTab('notes');document.body.classList.toggle('list-open');break;case 'new':notes.unshift({title:'Новая заметка',body:'Запишите первую мысль.',preview:'Новая запись',tag:'Личное',date:'Только что'});current=0;switchTab('notes');toast('Создана демонстрационная заметка');break;case 'edit':if(tab!=='notes'){toast('Откройте заметку для редактирования');break}$('#sheet').innerHTML='<div class="eyebrow">Редактирование · демо</div><h1>'+escapeHTML(notes[current].title)+'</h1><textarea class="edit-area" aria-label="Текст заметки">'+escapeHTML(notes[current].body)+'</textarea><p class="muted" style="font-size:12px">Изменения останутся в памяти макета до обновления страницы.</p><button class="primary" data-action="save">Сохранить в макете</button>';break;case 'save':notes[current].body=$('.edit-area').value;showNote();renderList();toast('Изменения сохранены в памяти макета');break;case 'history':modal('История заметки','<p><strong>Сегодня, 10:42</strong><br>Добавлены задачи и материалы проекта.</p><p><strong>Вчера, 19:10</strong><br>Создан первоначальный план.</p><p class="muted">Пример экрана истории. Восстановление версии описано в ТЗ.</p>');break;case 'transfer':modal('Передать копию','<p>'+escapeHTML(a.closest('tr')?.cells[0].textContent||'Материалы проекта.pdf')+' · '+escapeHTML(a.closest('tr')?.cells[1].textContent||'2,4 МБ')+'</p><label for="receiver">Устройство получателя</label><select id="receiver"><option>Личный компьютер · macOS</option><option>Рабочий ноутбук · Windows</option></select><p class="muted">Демонстрация интерфейса: настоящий файл не отправляется.</p>','transfer');break;case 'upload':modal('Добавить файл','<p>В приложении здесь будут выбор файла и перетаскивание. После загрузки файл появится на других устройствах.</p><p class="muted">Визуальный прототип не принимает и не загружает ваши файлы.</p>');break;case 'download':toast('Демо: файл будет загружен для офлайн-доступа');break;case 'sync':modal('Состояние синхронизации','<p><strong>'+$('#sync-text').textContent+'</strong></p><p>В готовом приложении здесь будут время последнего обмена, очередь изменений и ошибки передачи.</p><p class="muted">Статусы в макете демонстрационные.</p>');break;}});
document.addEventListener('change',e=>{if(e.target.matches('[data-task]')){tasks[Number(e.target.dataset.task)].done=e.target.checked;toast('Состояние задачи изменено в макете')}});
$('#search').addEventListener('input',renderList);$('#dialog-close').onclick=()=>$('#dialog').close();$('#dialog-confirm').onclick=()=>{if($('#dialog-confirm').dataset.confirm==='transfer'){const receiver=$('#receiver').value;$('#dialog-confirm').hidden=true;$('#dialog-body').innerHTML='<p>Демонстрационная передача: '+escapeHTML(receiver)+'</p><progress max="100" value="0" aria-label="Прогресс передачи"></progress><p id="progress-label">Подготовка…</p>';let p=0;const timer=setInterval(()=>{if(!$('#dialog').open){clearInterval(timer);return}p+=20;$('progress').value=p;$('#progress-label').textContent=p+'%';if(p>=100){clearInterval(timer);$('#progress-label').textContent='Демо завершено. Реальные данные не передавались.'}},240);}else $('#dialog').close()};
const statuses={synced:'Синхронизировано · демо',offline:'Нет сети · сохранено на устройстве',syncing:'Синхронизация · 2 изменения',error:'Не удалось синхронизировать'};const state=new URLSearchParams(location.search).get('state')||'synced';$('#sync-text').textContent=statuses[state]||statuses.synced;
renderList();showNote();
